baseURL = "https://seki.media"
languageCode = "en-us"
title = "関.media"
theme = "hugo-nederburg-theme"

# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[privacy]
  # Google Analytics privacy settings - https://gohugo.io/about/hugo-and-gdpr/index.html#googleanalytics
  [privacy.googleAnalytics]
    # set to true to disable service 
    disable = true
    # set to true to meet General Data Protection Regulation (GDPR)
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true

[params]
  # Unmark to use post folder for images. Default is static folder.
  #usepostimgfolder = true
  slogan = "Seki.media is a digital media cooperative."
  description = "Please, browse our work and consult us on your next media endeavor" # meta description
  # You need to set author to have an author bio. If you have a writer in the markdown file it will override this.
  author = "John Emory"
  authorLink = "https://github.com/jfemory/"
  bio = [
    "John is trained as a mathematician and enjoys programing, photography, and go."
  ]
  copyright = [
    "&copy; 2019 Seki.life",
  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "john@seki.life"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

  [[menu.main]]
  name = "Contact Us"
  url = "contact/"
  weight = 3

# this will also be in author bio if there is no writer.
  [params.social]
  email         = "john@seki.media"
  twitter       = "full profile url in twitter"
  github        = "https://github.com/jfemory"
  stackoverflow = "https://stackexchange.com/users/14016738/john-emory"

# Add a writer, then use it in the markdown front matter like this: writer = "Lukas Herman"
  [params.writers]
    [params.writers."John Emory"]
    link = "https://seki.dev"
    email = "john@seki.life"
    bio = [
"John is trained as a mathematician and enjoys programing, photography, and go."
    ]
    twitter       = "full profile url in twitter"
    stackoverflow = "https://stackexchange.com/users/14016738/john-emory"
    github        = "https://github.com/jfemory"

    [params.writers."Anthony Inman"]
    link = "https://seki.life/"
    email = "anthony@seki.life"
    bio = [
      "Anthony is our expert photographer."
    ]
    facebook      = "full Göran profile url in facebook"
    googleplus    = "full profile url in googleplus"
    twitter       = "full profile url in twitter"
    linkedin      = "full profile url in linkedin"
    stackoverflow = "full profile url in stackoverflow"
    instagram     = "full profile url in instagram"
    github        = "full profile url in github"
    pinterest     = "full profile url in pinterest"
